backend:
  name: github
  repo: charitytabernacleagbor-blip/charity-tabernacle-agbor
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "announcements"
    label: "Announcements"
    folder: "content/announcements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Message", name: "body", widget: "text" }
